### ISSUE TITLE
Wiki page of the Airflow Hands-on

### ISSUE THREAD

**Issue by simonlju-amazon** [qyjohn/Hands-on-Linux#1]
Is there a reason for not start Airflow with port 80 directly, but forward with a Apache web server?

**Comment by qyjohn** [comment]
Ports 1-1023 are privileged ports. To bind to a privileged port, a process must be running with root permissions. In the case of Airflow in standalone mode, we will need to run "airflow standalone" with **sudo**. 

Now, Airflow is started with root permissions. When Airflow runs untrusted customer code (defined in the DAG's), the customer code inherits the root permissions. This is a security risk. 

By using Apache2 to forward port 80 to 8080, Airflow does not need to have root permissions. This mitigates the above-mentioned security risk, and provides the convenience of accessing Airflow on port 80.

**Comment by simonlju-amazon** [comment]
Thanks for you detailed explanation and great idea!
